### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#51] opened 2017-03-22 15:32 UTC
`aqd` service should be released with a `systemd` integration script to replace the current `initd` script that doesn't support `chkconfig --add`.

**Comment by stdweird** [comment] 2017-03-22 15:33
is `systemctl enable aqd.service` supported?

**Comment by jrha** [comment] 2017-03-22 15:34
Duplicate of #43.

**Closed as completed by jrha** 2017-03-22 15:34 UTC
Labels: duplicate
