### ISSUE TITLE
Failure to create a domain left the Git branch created

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#52] opened 2017-03-22 16:30 UTC
If `aq add_domain` fails after the corresponding Git branch is created, it is left in the repository making creating the domain impossible until the branch has been removed manually. Aquilon should remove the created branch in such a case.

**Comment by urbonegi** [comment] 2017-04-04 17:13
There is a cleanup code that does this already:
https://github.com/quattor/aquilon/blob/upstream/lib/aquilon/worker/commands/add_domain.py#L83
However, if the branch delete (-D) actually fails, then the failed branch is left there. 

Could you provide more details, for this issue noticed. Logger message specifying the Exception would be the best to be able to determine why the deletion of the branch failed during a cleanup.

**Comment by urbonegi** [comment] 2017-04-27 11:50
@jouvin Could you please send the failure logs or help to clarify if the git branch delete failed on exception handling or something else did happened?
Cause as i pointed out above there is a code that handle the failure to create a domain..

**Comment by urbonegi** [comment] 2017-05-25 14:15
Unable to reproduce the scenario where git branch (create) succeeds but git clone or any other following commands (not that there are any) fails in normal conditions.. Added some code to artificially cause exception on git clone, however, there is an error catching and branch deleting already is in place, in case of error there. 
The only things that comes to my mind are: git force delete branch fails (nothing we can do about it..) or exception catching is too weak - we can catch all Exceptions there potentially..
@jouvin waiting for comments with additional details, otherwise i might just close this one as unable to reproduce under normal conditions..

**Comment by urbonegi** [comment] 2017-05-25 16:32
As per discussion in private conversation with @gombasg this issue can occur if commit() fails in the broker.py invoke_render method, therefore, there is no easy fix in scope of this command. Also this is rare corner case. If this happens user should just trigger repair script:
./sbin/aqd_consistency_check.py --repair

**Closed as completed by urbonegi** 2017-05-25 16:32 UTC
Labels: bug
