### ISSUE TITLE
Error when installing aquilon 1.11.24_rc1-1.noarch

### ISSUE THREAD

**Issue by guillaume-philippon** [quattor/aquilon#20] opened 2015-03-05 10:03 UTC
Hi,

After installing aquilon-protocol by the hand (issue #16 ), when I try to install aquilon I ve got the following error [1].

Regards;

[1]
  Installing : aquilon-1.11.24_rc1-1.noarch                                                                                                                                                                                             72/74 

Unhandled Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>

  File "/usr/lib64/python2.6/site-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib64/python2.6/site-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib64/python2.6/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib64/python2.6/site-packages/twisted/python/reflect.py", line 506, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.6/site-packages/twisted/plugins/aqd.py", line 34, in <module>
    from aquilon.worker.knc_protocol import KNCSite
  File "/usr/lib/python2.6/site-packages/aquilon/worker/knc_protocol.py", line 19, in <module>
    from twisted.web import http
exceptions.ImportError: No module named web
  Installing : aquilon-postgresql-1.0.0-1.noarch

**Comment by JulienNauroy** [comment] 2015-04-10 13:52
I'm stuck at the same point. Did you find a workaround?

**Comment by samary** [comment] 2015-04-13 09:44
I think you need to install this rpm : python-twisted-web

**Comment by JulienNauroy** [comment] 2015-04-15 15:11
I confirm the error disappears after installing python-twisted-web (on a fresh install).

**Comment by samary** [comment] 2015-04-17 12:04
IMHO, this should be handled by RPM dependencies.

**Comment by jrha** [comment] 2015-04-17 12:40
Indeed it should.

**Comment by urbonegi** [comment] 2017-09-29 12:40
Issue was created to resolve all RPM dependencies: https://github.com/quattor/aquilon/issues/48
And actually the RPM dependecies were updated, could someone check if the issue is gone now:
@samary @JulienNauroy @jrha

**Comment by ned21** [comment] 2017-10-26 13:57
Fixed by #48

**Closed as completed by ned21** 2017-10-26 13:57 UTC
Labels: Packaging
